### PR TITLE
Create Repositories architecture

### LINKED ISSUE #170: Refactoring the codebase
This refactor was **NEEDED**

### PR DESCRIPTION
**Pull request by dhalilov**
# Description

This is a draft PR to show progress and have feedback on a proposed data architecture change to follow [Android's best practices on the data layer](https://developer.android.com/topic/architecture/data-layer).

To briefly summarize the new architecture:

- `Repositories` are responsible for managing data sources and calling the appropriate methods between them. If you had a local cache, as well as a network source, you would manage the order of calls here (cache-first or network-first).
In our case, Firebase handles offline calls, so we only need to call the appropriate `get`/`setValue` here.
One important point to make here: there is one `Repository` per responsibility, i.e. the `ChallengeRepository` handles creation and fetching of challenges, no more, no less. This will make our life much easier than having a monolithic `FirebaseDatabase`.
- `ViewModels` will bridge the UI with the data layer by calling the methods of the `Repository` specific to the desired action, e.g. `challengeRepository.createChallenge` to create a challenge. A `ViewModel` holds the business logic: it reacts to UI events (e.g. clicks) by transferring the action to the associated repository, and might make some transformations on it/join data with other repositories. More importantly, it **holds data**. This means that it has full control over how and when the data is fetched, and if necessary, when the data is refreshed.

To illustrate the benefits of this architecture, consider the action of fetching the number of followers of a user. There are 2 distinct ways a `FollowRepository` might expose the `getNumberOfFollowers` method: using [coroutines](https://developer.android.com/kotlin/coroutines) for fetching once, or [Kotlin flows](https://developer.android.com/kotlin/flow) to react to data changes on the database.
```kotlin
// If the repository uses database read/writes, do not forget to use the IO dispatcher !
// For coroutines: withContext(Dispatchers.IO)
// For flows: flowOn(Dispatchers.IO)
class FollowRepository(
    private val database: FirebaseDatabase = FirebaseDatabase.getInstance()
) {
   // This is a suspend fun a.k.a a coroutine: it acts like a regular function, except it can be stopped (suspended)
   // at any time. It more or less represents async operations that are done once.
   suspend fun getNumberOfFollowers(user: User): Long = ...

   // This is a flow: it observes changes on the database and emits the change when the value is updated.
   // Notice there is no suspend here.
   fun getNumberOfFollowers(user: User): Flow<Long> = ...
}
```

The `ViewModel` can then use this repository to its advantage:
```kotlin
class FollowViewModel: ViewModel() {
    private val followRepository = FollowRepository()

    // We use an underlying field to prevent external mutation on the state
    private val _numberOfFollowers: MutableStateFlow<Long> = MutableStateFlow(0)
    val numberOfFollowers: StateFlow<Long> = _numberOfFollowers.asStateFlow() // returns a read-only state flow
    
    init {
        viewModelScope.launch {
            // For a coroutine, call it once like this:
            _numberOfFollowers.value = followRepository.getNumberOfFollowers(...)
            // If necessary, we can create a function to manually refresh the number by using the same code

            // For a flow, collecting will start listening for values
            // A flow is not triggered until it is collected
            followRepository.getNumberOfFollowers(...).collect { number -> _.numberOfFollowers.value = number }
        }
    }
}
```

Finally, `ViewModels` can be injected in the UI, but **only in top-level, screen Composables**. In most cases, lower-level composables should only use the data provided by the parent composable.

This is still a Work-In-Progess: many features are not migrated yet, and `ViewModels` are not created.

# Related issues

Closes #170

### CODE REVIEW

**Comment by Maeeen** [comment]
I really like the overall structure that it takes. Looks way easier and less barbarian than before!

**Comment by BoyeGuillaume** [comment]
The overall structure seems fine by me. It will certainly ease the process of writing UI code and linked it with the database.

**Comment by AlbanTrincherini** [comment]
Seems good overall, a better organization of our code base is really needed to make coding easier I think 👍

**Comment by Nicoslz** [comment]
From what I can see, the proposed structure appears to be a step in the right direction. Improving the organization of our code base will undoubtedly make our coding process smoother and more efficient!

**Review by AlbanTrincherini — APPROVED** [review]
Since we were 4 to work on this refactor, I think it is ok 👍

**Comment by Maeeen** [comment]
A

**Pull request merged**
